name: Conda to Miniforge Migration

on:
  pull_request:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Miniforge wget
      run: |
        wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"

    - name: Miniforge bash
      run: |
        bash Miniforge3.sh -b -p "${HOME}/conda"
        source "${HOME}/conda/etc/profile.d/conda.sh"
        source "${HOME}/conda/etc/profile.d/mamba.sh"

    - name: conda info
      run: |
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda info
        conda list

    - name: Tree view
      run: |
          sudo apt-get install -y tree
          tree .

    - name: Recreate environments in Miniforge
      shell: bash -l {0}
      run: |
        source "${HOME}/conda/etc/profile.d/conda.sh"
        
        # Recreate environments
        for env_file in ./miniconda_envs_backup/*.yml; do
          env_name=$(basename "$env_file" .yml)
          conda env create -f "$env_file" -n "$env_name"
        done

    - name: Verify Miniforge environments
      shell: bash -l {0}
      run: |
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda env list
        conda activate env1
        python -c "import numpy; import pandas; print('env1 OK')"
        conda activate env2
        python -c "import scipy; import matplotlib; print('env2 OK')"
